APP_HOST: 'madetector.localhost'
APP_PORT: '3000'

MAIL_SENDER: 'yourname+madetector@example.com'
MAIL_HOST: ''
MAIL_USERNAME: ''
MAIL_PASSWORD: ''

SECRET_KEY_BASE: 'rake secret'

test:
  #SELENIUM_DRIVER: 'selenium_chrome'
  SELENIUM_DRIVER: 'selenium_chrome_headless'
